# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZZHxb' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZZHxb

pod 'Macaw'
pod 'Alamofire'
pod 'SnapKit'
pod 'Kingfisher'
pod 'ReactiveCocoa'
pod 'KeychainAccess'
pod 'SwiftyBeaver'
pod 'HandyJSON','~>4.0.0-beta.1'

#pod 'ZZLib', :path =>'/Users/lxz/Documents/github_lib/ZZLib'

end
